### ISSUE TITLE
malformed css file can cause a hang

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pagespeed/mod_pagespeed#1028]
```
incomplete unicode character can cause the parser to fail and spin.

fix in r4389    
```

Original issue reported on code.google.com by `jcrowell@google.com` on 5 Dec 2014 at 6:43

**Comment by jeffkaufman** [comment]
Fixed in https://github.com/pagespeed/mod_pagespeed/commit/780c03cf3affae21f408cdfd304f5aeefe353c3c
