### ISSUE TITLE
inline_google_font_css no longer works in Chrome

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pagespeed/mod_pagespeed#1040]
```
In modern Chrome, visit 
http://www.modpagespeed.com/inline_google_font_css.html?PageSpeedFilters=+inline
_google_font_css

refresh 10 times; you'll always see the non-inlined font CSS and the woff2 font.


Now try this in Firefox: it will inline as expected, with a woff font.

```

Original issue reported on code.google.com by `jmara...@google.com` on 5 Jan 2015 at 1:45

**Comment by Faycal79** [comment]
Hi, 
I have the same issue on apache 2.2 and pagespeed 1.9.

The same problem is on the example:
http://www.modpagespeed.com/inline_google_font_css.html?PageSpeed=on&PageSpeedFilters=inline_google_font_css

What is the solution? Using local storage for caching fonts?

**Comment by morlovich** [comment]
We just had a regression in this triggered by a change in the server end.
There is a fix in
https://github.com/pagespeed/mod_pagespeed/commit/0e79a08a7601bf5e48d51fb2299563fafbb63090

(but not sure if a next 1.9 point release is planned).  ... but a
workaround may be to make your webpage use an explicit
 utf8 encoding (we sometimes can't see one set via header add or the like,
though), and that may break stuff if it's using
a different charset...
