### ISSUE TITLE
Make !clean!time! Errors into warnings (or infos) and make them more descriptive

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pagespeed/mod_pagespeed#183]
```
Some people are getting a lot of warnings like:

[Thu Dec 30 19:41:22 2010] [error] [mod_pagespeed 0.9.11.5-293] /var/
mod_pagespeed/cache/!clean!time!:0: open input file (code=2 No such
file or directory)

These are not actually errors and are only a problem if they are happening more 
than about 2/hour. We should make the message more descriptive so that is clear.
```

Original issue reported on code.google.com by `sligocki@google.com` on 10 Jan 2011 at 7:00

**Comment by techrah** [comment]
Can someone please explain what the !clean!time! file is and why it keeps reappearing after I've completely removed ALL files and subfolders from my mod_pagespeed cache directory? I've been searching for some kind of explanation of this and I can't find anything anywhere. Thanks in advance.

**Comment by jlporter** [comment]
mod_pagespeed has a periodic cache cleaning process to keep the cache from growing too large. By default it runs every 1 hour. That `!clean!time!` file is used to track when the last time cache cleaning was run, and will be regenerated each time cache cleaning runs. It's essentially an implementation detail, so we don't have that file explicitly documented, but you can read more about the cache cleaning process [here](https://developers.google.com/speed/pagespeed/module/system).

**Comment by techrah** [comment]
Thanks for the explanation Jud. Now I know my mod_pagespeed is working as it should w.r.t. that file.
