### ISSUE TITLE
Support ModPagespeedMapProxyDomain to CDN

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pagespeed/mod_pagespeed#599]
```
Currently I believe it is difficult to configure mod_pagespeed to take an 
externally-hosted resource, optimize it, and map it to a CDN.


Original message:


From Kim Frederiksen kim@olicity.com via googlegroups.com 
12/22/12 (11 days ago)


I have successfully configured the following directive using a subdomain, as it 
seems using a main domain with a WordPress .htaccess is not working. My 
directive is as follows:

ModPagespeedMapProxyDomain http://p.djoystick.com/proxyimages0 
http://distilleryimage0.s3.amazonaws.com

My question is, as I tried to after this directive using: 

ModPagespeedMapRewriteDomain http://pscdn.djoystick.com http://p.djoystick.com

Where pscdn.djoystick.com is a CNAME pointing to my CDN, using origin pull from 
p.djoystick.com

My hopes were to first proxy the resource, then use origin pull from my CDN to 
store the ressource in it's optimized form on the CDN.

Is that not possible, or am I making a flawed configuration? Also, what would 
you recommend in terms of using the original domain as the proxy instead of a 
subdomain under a wordpress root installation having .htaccess in that 
installation rewrite everything?
```

Original issue reported on code.google.com by `jmara...@google.com` on 2 Jan 2013 at 2:31

**Comment by binir** [comment]
I have too configured mod_pagespeed to take an externally-hosted resource for optimizing and mapping it to a CDN. Problem is only the .css are getting combined and optimized whereas there is no effect on .js files.

Filters enabled are configuration added is as follows:

```
ModPagespeedRewriteLevel PassThrough

ModPagespeedEnableFilters combine_css,extend_cache,rewrite_images,combine_javascript
ModPagespeedEnableFilters rewrite_css,rewrite_javascript
ModPagespeedEnableFilters inline_css,inline_javascript,rewrite_javascript_inline
ModPagespeedEnableFilters rewrite_javascript_external,rewrite_javascript_inline,outline_javascript
```

Is something missing in the configuration?

**Comment by oschaaf** [comment]
@binir Are the involved js files served as cacheable? If PageSpeed sees cache-control headers such as nocache or private it will not optimize.

**Comment by binir** [comment]
Yes cache-control header was private. Changed to public and its working now. 
Thank you.

**Comment by aelsharawi** [comment]
Hi

I m using Nginx, and my website is under https 

I use these setting but looks like it is not working

```
######## ADD CDN


pagespeed MapRewriteDomain https://mydomain https://wordpresscdn.azureedge.net;

pagespeed ShardDomain https://mydomain https://wordpresscdn.azureedge.net;
pagespeed MapProxyDomain https://mydomain/wp-content https://wordpresscdn.azureedge.net/wp-content;
pagespeed Domain https://wordpresscdn.azureedge.net;
#####
```

please help me

**Comment by jmarantz** [comment]
If I'm inferring what you are trying to do correctly, then you have the
arguments to MapRewriteDomain backwards.  From
https://developers.google.com/speed/pagespeed/module/domains#mapping_rewrite
:

pagespeed MapRewriteDomain domain_to_write_into_html
                           domain_specified_in_html;

If you have:
   https://mydomain/foo.html containing  <img src="bar.jpg" />
and you specify:
  pagespeed MapRewriteDomain https://wordpresscdn.azureedge.net
https://mydomain;
then the HTML will be rewritten as:
   <img src="https://wordpresscdn.azureedge.net/xbar.jpg.pagespeed.ic.HASH.webp"
/>
This requires that wordpresscdn.azureedge.ne
https://wordpresscdn.azureedge.net/t is set up as a pull CDN with origin
http://mydomain.

Hope this helps,
-Josh

**Comment by aelsharawi** [comment]
Yes, but not working

**Comment by jmarantz** [comment]
Ahmad -- can you open up a new issue by clicking this: https://github.com/pagespeed/ngx_pagespeed/issues/new and then describing in more detail exactly what you have in your config and what you are observing?  If possible, please provide a URL to your site.

Also, do you have
   pagespeed EnableFilters rewrite_domains;
in your config?

**Comment by aelsharawi** [comment]
I did not enable that 
pagespeed EnableFilters rewrite_domains;

--may be it is the whole problem?

I will try and see

**Comment by aelsharawi** [comment]
still did not work

may be Im writing the setting wrongely

please confirm that Im doing correctly before making a new issue

-I think azure akami cdn support origin pull??

===again my settings are:

```
######## ADD CDN
pagespeed EnableFilters rewrite_domains;

pagespeed MapRewriteDomain https://zzzz https://zz.azureedge.net;

pagespeed ShardDomain https://zzzz https://zz.azureedge.net;
pagespeed MapProxyDomain https://zzzzz/wp-content https://zzz.azureedge.net/wp-content;
pagespeed Domain https://zzz.azureedge.net;

#####

```

is there a problem in my settings?

**Comment by aelsharawi** [comment]
is it related to strict https ??

**Comment by jmarantz** [comment]
This is an ancient bug that is already closed.  Please send further
discussion & requests for help to
https://groups.google.com/forum/#!forum/mod-pagespeed-discuss , or add a
new bug to discuss this issue.

**Comment by aelsharawi** [comment]
Im so sorry to post here one more time

I found this error in the nginx log

```
 [ngx_pagespeed 1.11.33.0-0] No threading detected. Own threads: 1 Rewrite, 1 Expensive Rewrite.
2016/05/20 03:24:57 [info] 10447#10447: pagespeed: rollback gzip, explicit configuration in /etc/nginx/global/gzip.conf:2
```

and this is the file:
/etc/nginx/global/gzip.conf

```
# Enable Gzip compression.
gzip on;

# Disable Gzip on IE6.
gzip_disable "msie6";

# Allow proxies to cache both compressed and regular version of file.
# Avoids clients that don't support Gzip outputting gibberish.
gzip_vary on;

# Compress data, even when the client connects through a proxy.
gzip_proxied any;

# The level of compression to apply to files. A higher compression level increases
# CPU usage. Level 5 is a happy medium resulting in roughly 75% compression.
gzip_comp_level 5;

# The minimum HTTP version of a request to perform compression.
gzip_http_version 1.1;

# Don't compress files smaller than 256 bytes, as size reduction will be negligible.
gzip_min_length 256;

# Compress the following MIME types.
gzip_types
        application/atom+xml
        application/javascript
        application/json
        application/ld+json
        application/manifest+json
        application/rss+xml
        application/vnd.geo+json
        application/vnd.ms-fontobject
        application/x-font-ttf
        application/x-web-app-manifest+json
        application/xhtml+xml
        application/xml
        font/opentype
        image/bmp
        image/svg+xml
        image/x-icon
        text/cache-manifest
        text/css
        text/plain
        text/vcard
        text/vnd.rim.location.xloc
        text/vtt
        text/x-component
        text/x-cross-domain-policy;
  # text/html is always compressed when enabled.


```

**Comment by oschaaf** [comment]
@aelsharawi those are informational messages, you can ignore them.

**Comment by aelsharawi** [comment]
@oschaaf thanks, can u help me in resolving the CDN issue please?
