### ISSUE TITLE
Apache cannot restart if too many mutices from stats remain from unclean exits

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pagespeed/mod_pagespeed#71]
```
Originally eported by bogdan2ky, Nov 03, 2010, on the Page Speed issue tracker 
here: http://code.google.com/p/page-speed/issues/detail?id=389

------------------------

Mod was enabled and worked for a while, it was correctly speeding'up all of my 
sites:
cs.dude.ro, sportarges.ro, anvelopepitesti.ro etc.
then i played with the rewrite options in pagespeed.conf of 
/mod_pagespeed_beacon and /mod_pagespeed_statistics location, afer that apache 
won't work until i comment out the "LoadModule pagespeed_module"
Apache/2.2.11 (Ubuntu)
Ubuntu 9.04
PHP 5.2.6-3ubuntu4.6

apache error logs attached..
```

Original issue reported on code.google.com by `mdste...@google.com` on 11 Nov 2010 at 2:52

Attachments:
- [apache.error.log](https://storage.googleapis.com/google-code-attachments/modpagespeed/issue-71/comment-0/apache.error.log)

**Comment by didiandalucia** [comment]
The Problem is not resolved! We get in Version mod_bw Version 0.92 the same problem and every day the vserver hang with mod_bw Memory Allocated 0 bytes, but the server has 7 GB RAM free!

Under https://wiki.1awww.com/index.php?title=Plesk-Panel_Auto-Update_Probleme we have written a workarround!

**Comment by jmarantz** [comment]
didiandalucia: is your issue related to mod_pagespeed?  Note that this issue has been fixed since early 2011 and we haven't heard any other complaints of this since then (in our migration from Google Code to Github, the dates on the comments got a little confusing).

It sounds like what you observed is only an issue for mod_bw.

**Comment by didiandalucia** [comment]
Yes this is about mod_bw. I have found a other project in sourceforge with bw_mod. Thanks for answer
