### ISSUE TITLE
Make maximum image size configurable

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pagespeed/mod_pagespeed#757]
```
What steps will reproduce the problem?
1. Trying to resize an image with ratio 3000x2000

What is the expected output? What do you see instead?

expected resized image - got original


What version of the product are you using (please check X-Mod-Pagespeed
header)?

1.4.26.3-3101

On what operating system?

debian

Which version of Apache?

2.2

Is there any hardcoded limitation of maximum image size while trying to resize 
an image. If yes, this should be a setting in the configuration.

Thanks
Jan


```

Original issue reported on code.google.com by `grasba...@googlemail.com` on 30 Jul 2013 at 7:25

**Comment by tomasdev** [comment]
Any chance on plans of making the resize configurable rather than based off user viewport? I.e., if a site contains an image 4000x4000, to be able to specify "maxresizeside = 2000"  and that resizes and optimizes to 2000x2000 ? (or 2000x1000 if it were a 6000x3000 original)
